steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/awesome-treat-404710/dev-network-api/network-api:dev', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/awesome-treat-404710/dev-network-api/network-api:dev']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'dev-network-api', '--image', 'us-central1-docker.pkg.dev/awesome-treat-404710/dev-network-api/network-api:dev', '--region', 'us-central1', '--allow-unauthenticated']

options:
  logging: CLOUD_LOGGING_ONLY
