/api/auth/login:
   post:
     tags: [Auth]
     summary: Authenticate user credentials
     requestBody:
       required: true
       content:
         application/json:
           schema:
             $ref: '#/components/schemas/LoginRequest'
     responses:
       '200':
         description: Successful login
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/LoginResponse'
       '401':
         description: Invalid credentials