/api/auth/change-password:
   post:
     tags: [Auth]
     summary: Change - After OTP Verification
     requestBody:
       required: true
       content:
         application/json:
           schema:
             $ref: '#/components/schemas/ChangePasswordRequest'
     responses:
       '200':
         description: Password changed successfully
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/LoginResponse'
       '400':
         description: Invalid request